name: GitHub Actions Build and Deploy Demo
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Install and Build
      run: sleep 30s
  build-and-deploy1:
    runs-on: ubuntu-latest
    needs: [build-and-deploy]
    if: cancelled()
    steps:
    - name: Install and Build
      run: sleep 30s
  build-and-deploy2:
    runs-on: ubuntu-latest
    needs: [build-and-deploy1]
    if: success()
    steps:
    - name: run in cancelled
      if: cancelled()
      run: sleep 30s
    - name: Install and Build
      run: sleep 30s
    - name: run in cancelled1
      if: cancelled()
      run: sleep 30s
  build-and-deploy3:
    runs-on: ubuntu-latest
    needs: [build-and-deploy1]
    if: success()
    steps:
    - name: run in cancelled
      if: cancelled()
      run: sleep 30s
    - name: Install and Build
      run: sleep 30s
    - name: run in cancelled1
      if: cancelled()
      run: sleep 30s
  build-and-deploy4:
    runs-on: ubuntu-latest
    needs: [build-and-deploy2, build-and-deploy3]
    if: cancelled()
    steps:
    - name: Install and Build
      run: sleep 30s
