name: GitHub Actions Build and Deploy Demo
on:
  push:
    branches:
      - master
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: step1
        if: always()
        run: sleep 120s
  job2:
    runs-on: ubuntu-latest
    steps:
      - name: step1
        if: always()
        run: sleep 120s
  job3:
    runs-on: ubuntu-latest
    needs: "${{ vars.TEST_NEEDS }}"
    steps:
      - name: step1
        if: always()
        run: sleep 120s
