name: GitHub Actions Build and Deploy Demo
on:
  push:
    branches:
      - master
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: step1
        run: for b in {1..1000} ;do echo "hello world"; sleep 1; done;
      - name: step2
        run: for b in {1..1000} ;do echo "hello world"; sleep 1; done;
