name: GitHub Actions Build and Deploy Demo
on:
  push:
    branches:
      - master
env:
  TEST_NAME: zhangtanglei
jobs:
  job1:
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      output1: ${{ steps.step1.outputs.test }}
      output2: ${{ steps.step2.outputs.test }}
    steps:
      - id: step1
        name: test
        env: 
          Map: $TEST_NAME
        run: echo "map=${{env.Map}}" && echo -e "import os" >> test1.py && echo -e "print(os.environ['Map'])" >> test1.py && python test1.py
      - id: step2
        name: test
        run: echo "test=world" >> "$GITHUB_OUTPUT"
  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - env:
          OUTPUT1: ${{needs.job1.outputs.output1}}
          OUTPUT2: ${{needs.job1.outputs.output2}}
        run: echo "$OUTPUT1 $OUTPUT2"
