name: GitHub Actions Build and Deploy Demo
on:
  push:
    branches:
      - master
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
    - name: Install and Build
      run: echo vars defined name is $MY_NAME
  job2:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.step1.outputs.test }}
    steps:
    - id: step1
      run: echo "test=hello" >> "$GITHUB_OUTPUT"
  job3:
    runs-on: ubuntu-latest
    needs: [job1, job2]
    if: NEEDS.JOB2.OUTPUTS.OUTPUT1 == 'hello'
    steps:
    - name: sleep1
      run: sleep 30s
