name: GitHub Actions Build and Deploy Demo
on:
  push:
    branches:
      - master
jobs:
  job1:
    runs-on: ubuntu-latest
    env:
      MY_NAME: "env"
    steps:
    - name: error
      run: lssss
    - name: success
      if: failure()
      run: ls
    - name: success
      if: failure()
      run: ls
