name: GitHub Actions Build and Deploy Demo
on:
  push:
    branches:
      - master
jobs:
  job1:
    runs-on: ubuntu-latest
    env:
      MY_NAME: "env"
    if: always()
    steps:
    - name: test always() cancelled
      run: sleep 300s
