name: GitHub Actions Build and Deploy Demo
on:
  push:
    branches:
      - master
jobs:
  job1:
    runs-on: ubuntu-latest
    env:
      MY_NAME: "env"
    steps:
    - name: failed step
      run: ls
    - name: test success() default
      if: env.MY_NAME == 'env'
      run: ls
    - name: test success() default when expression not status-check-func
      run: ls
