name: GitHub Actions Build and Deploy Demo
on:
  push:
    branches:
      - master
jobs:
  job1:
    env:
      VARF: false
      VART: true
    runs-on: ubuntu-${{ 'latest' }}
    steps:
      - name: Var test
        run: |
          echo "VART=${{ env.VARF }}"
          echo "VART=${{ env.VART }}"
          echo "VARF && VART=${{ env.VARF && env.VART }}"
          echo "VARF || VART=${{ env.VARF || env.VART }}"
          echo "!VARF=${{ ! env.VARF }}"
          echo "!!VART=${{ !! env.VART }}"
