name: GitHub Actions Build and Deploy Demo
on:
  push:
    branches:
      - master
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: step1
        run: ls
      - name: step2
        if: false
        run: ls
  job2:
    runs-on: ubuntu-latest
    if: false
    steps:
      - name: step1
        run: ls
      - name: step2
        run: ls
