name: GitHub Actions Build and Deploy Demo
on:
  push:
    branches:
      - master
jobs:
  job1:
    runs-on: ubuntu-latest
    env:
      MY_NAME: "env"
    steps:
    - name: expect success
      run: ls
    - name: expect skipped
      if: env.MY_NAME != 'env'
      run: ls
    - name: test skipped step for default success()
      run: ls
    - name: test skipped step for success()
      if: success()
      run: ls
