name: GitHub Actions Build and Deploy Demo
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Install and Build
      run: sleep 20s
  build-and-deploy1:
    runs-on: ubuntu-latest
    needs: [build-and-deploy]
    if: failure()
    steps:
    - name: Install and Build
      run: sleep 10s
  build-and-deploy2:
    runs-on: ubuntu-latest
    needs: [build-and-deploy1]
    if: ${{ !failure() && !cancelled() }}
    steps:
    - name: Install and Build
      run: sleep 10s
