name: GitHub Actions Build and Deploy Demo
on:
  push:
    branches:
      - master
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: step1
        if: always()
        run: sleep 1s
  job2:
    runs-on: ubuntu-latest
    steps:
      - name: step1
        if: always()
        run: sleep 1s
  job3:
    runs-on: ubuntu-latest
    needs: ${{ 'job1' }}
    steps:
      - name: step1
        if: always()
        run: sleep 2s
