name: GitHub Actions Build and Deploy Demo
on:
  push:
    branches:
      - master
jobs:
  job1:
    env:
      VARF: false
      VART: true
    runs-on: ubuntu-${{ 'latest' }}
    steps:
      - name: Var test
        run: java -version
