name: GitHub Actions Build and Deploy Demo
on:
  push:
    branches:
      - master
jobs:
  job1:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - run: lsssss
  job2:
    runs-on: ubuntu-latest
    needs: [job1]
    if: success()
    steps:
      - run: ls
  job3:
    runs-on: ubuntu-latest
    needs: [job1]
    if: failure()
    steps:
      - run: ls
