name: GitHub Actions Build and Deploy Demo
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Install and Build
      run: pwd
  build-and-deploy1:
    runs-on: ubuntu-latest
    needs: [build-and-deploy]
    if: failure()
    steps:
    - name: Install and Build
      run: pwd
  build-and-deploy2:
    runs-on: ubuntu-latest
    needs: [build-and-deploy]
    if: success()
    steps:
    - name: Install and Build
      run: pwd
  build-and-deploy3:
    runs-on: ubuntu-latest
    needs: [build-and-deploy1, build-and-deploy2]
    if: failure()
    steps:
    - name: Install and Build
      run: pwd
