name: GitHub Actions Build and Deploy Demo
on:
  push:
    branches:
      - master
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: step1
        run: sleep 120s
      - name: step2
        timeout-minutes: 1
        run: sleep 120s
      - name: step3
        run: sleep 120s
