name: GitHub Actions Build and Deploy Demo
on:
  push:
    branches:
      - master
jobs:
  job1:
    env:
      VARF: false
      VART: true
    runs-on: ubuntu-${{ 'latest' }}
    steps:
      - name: Var test
        run: |
          echo "json is {\"name\": \"ztl\"}"
          echo "VARF==false = ${{ env.VARF==false }}"
          echo "VARF=='false' = ${{ env.VARF=='false' }}"
          echo "VART==true = ${{ env.VART==true }}"
          echo "VART=='true' = ${{ env.VART=='true' }}"
