name: GitHub Actions Build and Deploy Demo
on:
  push:
    branches:
      - master
jobs:
  job1:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - name: step1
        if: always()
        run: sleep 30s
      - name: step2
        if: cancelled()
        run: sleep 12s
      - name: step3
        if: always()
        run: sleep 12s
