name: GitHub Actions Build and Deploy Demo
on:
  push:
    branches:
      - master
jobs:
  job1:
    runs-on: ubuntu-latest
    env:
      NAME: ${{ vars.MY_NAME }}
      TO_JSON: ${{ toJSON(['csharp', 'javascript']) }}
    steps:
      - run: echo TO_JSON=$TO_JSON
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: ${{ toJSON(['csharp', 'javascript']) }}
