name: GitHub Actions Build and Deploy Demo
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Install and Build
      run: sleep 10s
  build-and-deploy1:
    runs-on: ubuntu-latest
    needs: [build-and-deploy]
    if: failure()
    steps:
    - name: Install and Build
      run: sleep 10s
  build-and-deploy2:
    runs-on: ubuntu-latest
    needs: [build-and-deploy1]
    steps:
    - name: Install and Build
      run: sleep 10s
    needs: [build-and-deploy2, build-and-deploy3]
    if: cancelled()
    steps:
    - name: Install and Build
      run: sleep 30s
